# Generated by Django 4.2.2 on 2023-12-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('Phone_No', models.IntegerField()),
                ('wallet', models.IntegerField()),
            ],
        ),
    ]
