# Generated by Django 4.2.2 on 2023-12-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizing', '0002_remove_profile_user_id_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone_No',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.BigIntegerField(),
        ),
    ]
