# Generated by Django 5.0 on 2023-12-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizing', '0003_alter_profile_phone_no_alter_profile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.CharField(max_length=50),
        ),
    ]
