# Generated by Django 4.2.2 on 2024-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizing', '0004_alter_profile_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('time_between_points', models.FloatField(default=0)),
            ],
        ),
    ]
