# Generated by Django 4.2.2 on 2024-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizing', '0005_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='time_between_points',
        ),
        migrations.AddField(
            model_name='score',
            name='quizName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
