# Generated by Django 4.2.2 on 2024-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizing', '0006_remove_score_time_between_points_score_quizname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
